name: Nix CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: tui-commander
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run code and formatting checks
        run: nix --print-build-logs flake check --show-trace
  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: tui-commander
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build documentation
        run: nix --print-build-logs build .#tui-commander-doc --show-trace
  gitlint:
    name: gitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: tui-commander
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check git messages in branch
        run: nix develop -c gitlint --commits $(git merge-base origin/master HEAD)..HEAD
  dead:
    name: deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: tui-commander
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run deadnix
        run: nix run github:astro/deadnix
  statix:
    name: statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: tui-commander
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run deadnix
        run: nix develop -c statix check
