name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # 03:15 every 1st of every 3rd month
    - cron: '15 3 1 */3 *'
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: T-dep-update
          inputs: nixpkgs
